[versions]
# Minecraft
paper-mc = "1.20.1-R0.1-SNAPSHOT"
plugin-yml = "0.6.0"
run-paper = "2.2.4"

# Hooks
placeholder-api = "2.11.5"

# Utils
lombok = "1.18.30"
gson = "2.10.1"

[libraries]
# Minecraft
papermc = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-mc" }

# Hooks
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholder-api" }

# Utils
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
# Minecraft
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "plugin-yml" }
runpaper = { id = "xyz.jpenilla.run-paper", version = "2.2.4" }
